version: "3.8"

services:
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    restart: always
    command: pnpm dev
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
